"""Capture D19 discovery/play journeys against the real built client and coordinator."""
import argparse,hashlib,json,subprocess,time
from pathlib import Path
from playwright.sync_api import sync_playwright

def main():
 parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,required=True);a=parser.parse_args();a.output.mkdir(parents=True,exist_ok=True);root=Path(__file__).resolve().parents[2];diagnostic=(root/'apps/client/dist/generated/diagnostic.nes').read_bytes();started=time.monotonic();service=subprocess.Popen(['node','scripts/rooms/browser-server.ts'],cwd=root,stdout=subprocess.PIPE,text=True)
 try:
  url=json.loads(service.stdout.readline())['url'];evidence={'states':{},'routes':{}}
  with sync_playwright()as pw:
   browser=pw.chromium.launch(channel='chrome',ignore_default_args=['--mute-audio']);errors=[]
   def page(width=1280,height=800):
    p=browser.new_page(viewport={'width':width,'height':height});p.on('pageerror',lambda e:errors.append(str(e)));p.goto(url);p.wait_for_function("document.querySelector('[data-testid=directory]')");return p
   def metrics(p,name):
    value=p.evaluate('''()=>({innerWidth,innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,bodyWidth:document.body.scrollWidth,bodyHeight:document.body.scrollHeight})''');assert value['scrollWidth']<=value['innerWidth']and value['scrollHeight']<=value['innerHeight'];evidence['states'][name]=value;return value
   wide=page();metrics(wide,'wide-discovery');assert wide.get_by_role('button',name='Play Super Tilt Bro').is_visible();assert wide.get_by_role('button',name='Play From Below').is_visible();assert wide.get_by_role('button',name='Choose NES file').is_visible();assert wide.get_by_role('button',name='Pause').count()==0;wide.screenshot(path=str(a.output/'wide-discovery.png'))
   wide.get_by_role('button',name='Play Super Tilt Bro').click();wide.wait_for_function("Number(document.querySelector('[data-testid=frames]').textContent.split(' ')[0])>30",timeout=30000);metrics(wide,'super-playing');before=int(wide.get_by_test_id('frames').inner_text().split()[0]);wide.screenshot(path=str(a.output/'super-playing.png'));wide.get_by_role('button',name='All lobbies').click();wide.get_by_test_id('directory').wait_for();time.sleep(.25);during=int(wide.get_by_test_id('frames').inner_text().split()[0]);assert during>before;metrics(wide,'all-lobbies-progressing');wide.get_by_role('button',name='Return to game').click();assert int(wide.get_by_test_id('frames').inner_text().split()[0])>=during;wide.get_by_role('button',name='Game help').click();assert 'License details pending' in wide.get_by_role('dialog').inner_text();metrics(wide,'game-help-dialog');wide.screenshot(path=str(a.output/'game-help.png'));wide.get_by_role('button',name='Close').click();wide.get_by_role('button',name='Pause').click();metrics(wide,'paused');evidence['routes']['super_tilt']={'playable':True,'progress_preserved':True,'frames_before_lobbies':before,'frames_after_lobbies':during}
   narrow=page(760,680);metrics(narrow,'narrow-discovery');narrow.screenshot(path=str(a.output/'narrow-discovery.png'));narrow.get_by_role('button',name='Play From Below').click();narrow.wait_for_function("Number(document.querySelector('[data-testid=frames]').textContent.split(' ')[0])>10",timeout=30000);metrics(narrow,'from-below-playing');narrow.screenshot(path=str(a.output/'from-below-playing.png'));narrow.get_by_role('button',name='Pause').click();evidence['routes']['from_below']={'playable':True}
   own=page();own.set_input_files('input[type=file]',{'name':'arbitrary-private.nes','mimeType':'application/octet-stream','buffer':diagnostic});own.wait_for_function("Number(document.querySelector('[data-testid=frames]').textContent.split(' ')[0])>10");own.get_by_test_id('room-view').wait_for();assert 'arbitrary-private' not in own.locator('body').inner_text();own.get_by_role('button',name='Pause').click();evidence['routes']['arbitrary']={'playable_and_hosted':True,'sha256':hashlib.sha256(diagnostic).hexdigest(),'filename_absent':True}
   invalid=page();invalid.set_input_files('input[type=file]',{'name':'invalid.nes','mimeType':'application/octet-stream','buffer':b'not a rom'});invalid.locator('.selection-status').wait_for();assert 'This is not an NES cartridge' in invalid.locator('.selection-status').inner_text();assert invalid.get_by_role('button',name='Choose NES file').is_visible();metrics(invalid,'invalid-recovery')
   hosts=[wide,narrow,own];
   for index in range(3):
    h=page();h.get_by_role('button',name='Play From Below' if index%2 else 'Play Super Tilt Bro').click();h.get_by_test_id('room-view').wait_for(timeout=30000);h.wait_for_function("Number(document.querySelector('[data-testid=frames]').textContent.split(' ')[0])>2");h.get_by_role('button',name='Pause').click();hosts.append(h)
   listing=page();listing.get_by_text('Page 1 of 2').wait_for();assert listing.locator('.room-list [data-room-id]').count()==3;listing.get_by_role('button',name='Next').click();listing.get_by_text('Page 2 of 2').wait_for();assert listing.locator('.room-list [data-room-id]').count()==3;assert listing.locator('.room-list').evaluate('e=>e.scrollHeight<=e.clientHeight');listing.screenshot(path=str(a.output/'multi-page-lobbies.png'));listing.get_by_label('Lobby pages').get_by_role('button',name='Previous').focus();listing.get_by_role('button',name='Previous').click();listing.wait_for_function("document.activeElement?.matches('.room-list [data-room-id]')");evidence['routes']['directory']={'rooms':6,'pages':2,'page_size':3,'focus_moves_to_first_row':True,'nested_scroll':False}
   listing.evaluate("document.documentElement.style.fontSize='125%'");metrics(listing,'large-text');listing.evaluate("document.documentElement.style.fontSize='100%'");listing.set_viewport_size({'width':800,'height':600});metrics(listing,'browser-zoom-equivalent-constrained');assert listing.get_by_role('button',name='Play Super Tilt Bro').is_visible();assert listing.get_by_role('button',name='Choose NES file').is_visible()
   assert not errors,errors;evidence.update({'result':'pass','browser':browser.version,'duration_seconds':round(time.monotonic()-started,2),'page_errors':errors,'limits':'Local same-origin coordinator and desktop Chrome; no Internet route, physical controller, assistive-technology session, or audible-device capture.'});(a.output/'browser.json').write_text(json.dumps(evidence,indent=2)+'\n');print(json.dumps(evidence,indent=2));browser.close()
 finally:
  service.terminate()
  try:service.wait(timeout=5)
  except subprocess.TimeoutExpired:service.kill();service.wait()
if __name__=='__main__':main()
