import {PlayControls} from './PlayControls.tsx';
import {VoiceControls} from './VoiceControls.tsx';
import type {VoiceState} from './voice.ts';
import {ConnectionPolicyControl,readConnectionPolicy,rememberConnectionPolicy} from './ConnectionPolicy.tsx';
import type {ConnectionPolicy} from '../../../packages/contracts/src/peer.ts';
import React, { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LocalPlayer, type PlayerState } from './player.ts';
import { neutralDefaults } from './cartridge.ts';
import { clientConfig } from './config.ts';
import './style.css';
import {RoomPanel, type RoomPanelHandle} from './RoomPanel.tsx';
import type {RoomState} from './room-client.ts';
import {LocalData} from './LocalData.tsx';
import {usePreferences} from './preferences.ts';
import {fileIdentity} from '../../../packages/contracts/src/fingerprint.ts';
import {downloadSave} from './saves.ts';
import { Rewind } from './Rewind.tsx';
import { Saves } from './Saves.tsx';
import { Settings } from './Settings.tsx';
import { defaults, bindingLabel, type Controls } from './controls.ts';
import {catalogEntry,catalogId} from '../../../packages/contracts/src/catalog.ts';
import type {RoomView} from '../../../packages/contracts/src/rooms.ts';
import {rememberImport,rememberPreview,capturePreview} from './rom-library.ts';
import {gameLibrary,savedCandidate,candidateStillStored,type GameLibraryEntry,type SavedCandidate} from './rom-library.ts';
import {CreateGame,type CreateSelection} from './CreateGame.tsx';
import {downloadCatalogEntry} from './catalog-download.ts';
import {catalogAvailability} from 'virtual:catalog';
import type {Fingerprint,Visibility} from '../../../packages/contracts/src/rooms.ts';

function App() {
 const canvas = useRef<HTMLCanvasElement>(null), picker = useRef<HTMLInputElement>(null);
 const runtime = useRef<LocalPlayer | null>(null);
 const panel = useRef<HTMLElement>(null);
 const [tool,setTool]=useState<'settings'|'localData'|'saves'|'rewind'|'help'|null>(null),[returnSettings,setReturnSettings]=useState(false),[persistenceMessage,setPersistenceMessage]=useState('');
 const toolReturnFocus=useRef<HTMLElement|null>(null);
 const toolReturnSelector=useRef<string|null>(null);
 const toolFocus=useRef<'heading'|'voice'|'settings-data'|'return'|null>(null);
 const [controls,setControls] = useState<Controls>(defaults);
 const [filter,setFilter] = useState<'nearest'|'scanlines'>('nearest'), [volume,setVolume] = useState(1);
 const [fullscreen,setFullscreen] = useState(false), [fullscreenIssue,setFullscreenIssue] = useState('');
 useEffect(()=>{const changed=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',changed);return ()=>document.removeEventListener('fullscreenchange',changed);},[]);
 useLayoutEffect(()=>{const next=toolFocus.current;toolFocus.current=null;if(next==='heading')document.querySelector<HTMLElement>('.tool-page h2')?.focus();else if(next==='voice')document.querySelector<HTMLElement>('.settings .voice-panel h3')?.focus();else if(next==='settings-data')document.querySelector<HTMLElement>('.settings button[data-local-data]')?.focus();else if(next==='return'){const target=toolReturnFocus.current,selector=toolReturnSelector.current;toolReturnFocus.current=null;toolReturnSelector.current=null;if(target?.isConnected)target.focus();else (selector&&document.querySelector<HTMLElement>(selector)||document.querySelector<HTMLElement>('header button'))?.focus();}},[tool]);
 const openTool=async(next:NonNullable<typeof tool>,fromSettings=false,focus:'heading'|'voice'='heading')=>{const opener=document.activeElement as HTMLElement;
  if(document.fullscreenElement){try{await document.exitFullscreen();}catch{setFullscreenIssue('Could not exit fullscreen. Press Esc, then try again.');return;}}
  setFullscreenIssue('');
  if(!fromSettings){toolReturnFocus.current=opener;toolReturnSelector.current=opener.closest('.voice-card')?'.voice-card .voice-settings':opener.closest('.play-controls')?'.play-controls .text-action':next==='settings'?'header button[data-settings]':null;}toolFocus.current=focus;setReturnSettings(fromSettings);setTool(next);};
 const backTool=()=>{if(tool==='localData'&&returnSettings){toolFocus.current='settings-data';setTool('settings');return;}toolFocus.current='return';setTool(null);};
 useEffect(()=>{if(!tool)return;const escape=(event:KeyboardEvent)=>{if(event.key!=='Escape'||event.defaultPrevented||event.target instanceof HTMLSelectElement)return;const cancel=document.querySelector<HTMLButtonElement>('.tool-page [role=alertdialog] button:last-child, .tool-page [aria-label="Confirm mapping reset"] button:last-child, .tool-page .capture button:last-child');if(cancel?.getClientRects().length){event.preventDefault();cancel.click();return;}event.preventDefault();backTool();};addEventListener('keydown',escape);return()=>removeEventListener('keydown',escape);},[tool,returnSettings]);
 const changeControls=(value:Controls)=>{setControls(value);runtime.current?.configureControls(value);preferences.remember({controls:value,filter,volume});};
 const toggleFullscreen=async()=>{try{setFullscreenIssue('');if(document.fullscreenElement) await document.exitFullscreen();else await panel.current?.requestFullscreen();}catch{setFullscreenIssue('Fullscreen was declined. You can keep playing in this window.');}};
 const [identity] = useState(neutralDefaults);
 const [guest,setGuest] = useState(identity.guest);
 const rooms = useRef<RoomPanelHandle>(null);
 const importFile=useRef<File|null>(null),previewed=useRef('');
 const [creating,setCreating]=useState(location.pathname==='/create'),[createStatus,setCreateStatus]=useState('Choose a game to continue.'),[claimFailed,setClaimFailed]=useState(false),[createSelection,setCreateSelection]=useState<CreateSelection>(),[selecting,setSelecting]=useState(false),[visibility,setVisibility]=useState<Visibility>('public'),[libraryRevision,setLibraryRevision]=useState(0);
 const creatingRoute=useRef(location.pathname==='/create');
 const [roomState,setRoomState]=useState<RoomState>({status:'',busy:false,connected:false});
 const createGeneration=useRef(0),selectionGeneration=useRef(0),createPending=useRef<{file:File;entry:GameLibraryEntry;saved?:SavedCandidate;fresh?:boolean;current:()=>boolean;sawLoading:boolean}|undefined>(undefined);
 const downloadAbort=useRef<AbortController|undefined>(undefined);
 const [voice,setVoice]=useState<VoiceState>();
 const [policy,setPolicy]=useState<ConnectionPolicy>(readConnectionPolicy),[connection,setConnection]=useState('No peer connection.');
 const changePolicy=(value:ConnectionPolicy)=>{runtime.current?.pause();rememberConnectionPolicy(value);setPolicy(value);};
 const load = (file?:File,selectionCurrent?:()=>boolean,verify?:(fingerprint:Fingerprint)=>Promise<boolean>):boolean => {if(!file||!runtime.current||selectionCurrent&&!selectionCurrent()||!selectionCurrent&&rooms.current?.beforeSelection()===false)return false;if(!selectionCurrent)importFile.current=file;else importFile.current=null;void runtime.current.load(file,async(fingerprint,isCurrent)=>{if(verify&&!await verify(fingerprint))return false;return rooms.current?.approveSelection(fingerprint,isCurrent) ?? isCurrent();},true,selectionCurrent);return true;};
 const [state,setState] = useState<PlayerState>({status:'Choose a game to start playing.',loading:false,running:false,loaded:false,frames:0});
 useEffect(()=>{if(!state.loaded||!state.fingerprint)return;const file=importFile.current;if(!file)return;importFile.current=null;void rememberImport(file,state.fingerprint.romSha256).then(()=>{setPersistenceMessage('');setLibraryRevision(value=>value+1);}).catch(()=>setPersistenceMessage('Available in this tab only. Browser storage did not save the game.'));},[state.loaded,state.fingerprint]);
 useEffect(()=>{const hash=state.fingerprint?.romSha256,frame=canvas.current;if(!hash||!frame||state.frames<1||state.frames%30!==0||previewed.current===hash)return;void capturePreview(frame).then(preview=>preview?rememberPreview(hash,preview):false).then(saved=>{if(saved)previewed.current=hash;}).catch(()=>{});},[state.frames,state.fingerprint]);
 useEffect(()=>{const pending=createPending.current;if(!pending)return;if(state.loading){pending.sawLoading=true;return;}if(!pending.sawLoading)return;createPending.current=undefined;if(!pending.current())return;setSelecting(false);if(state.loaded&&state.fingerprint&&state.fingerprint.romSha256===pending.entry.sha256&&runtime.current?.isLoaded(state.fingerprint)){const selectedGeneration=++selectionGeneration.current;setCreateSelection({entry:pending.entry,file:pending.file,fingerprint:state.fingerprint,current:()=>selectedGeneration===selectionGeneration.current&&location.pathname==='/create',fresh:pending.fresh});setCreateStatus(`${pending.entry.label} is loaded and ready.`);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.create-actions button')?.focus());if(pending.fresh)void rememberImport(pending.file,state.fingerprint.romSha256).then(()=>{setPersistenceMessage('');setLibraryRevision(value=>value+1);}).catch(()=>setPersistenceMessage('Available in this tab only. Browser storage did not save the game.'));}else setCreateStatus(state.status);},[state.loading,state.fingerprint,state.status]);
 const [browsing,setBrowsing]=useState(false),[roomView,setRoomView]=useState<RoomView>();
 const [invitationHash,setInvitationHash]=useState(location.hash);
 useEffect(()=>{const sync=()=>{setInvitationHash(location.hash);const nextCreating=location.pathname==='/create';if(creatingRoute.current&&!nextCreating){++createGeneration.current;++selectionGeneration.current;downloadAbort.current?.abort();createPending.current=undefined;setCreateSelection(undefined);setSelecting(false);rooms.current?.cancelCreation();requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.directory-title button')?.focus());}creatingRoute.current=nextCreating;setCreating(nextCreating);if(new URLSearchParams(location.hash.slice(1)).has('invite'))setBrowsing(false);else if(!nextCreating)setBrowsing(true);};addEventListener('hashchange',sync);addEventListener('popstate',sync);return()=>{removeEventListener('hashchange',sync);removeEventListener('popstate',sync);};},[]);
 const syncRoom=useCallback((room?:RoomView)=>{setRoomView(room);if(room){creatingRoute.current=false;setBrowsing(false);setCreating(false);if(location.pathname==='/create')history.replaceState(null,'','/');}},[]);
 const enterCreate=()=>{if(roomView)return;history.pushState(null,'','/create');creatingRoute.current=true;setCreating(true);setClaimFailed(false);setBrowsing(false);};
 const leaveCreate=()=>{++createGeneration.current;++selectionGeneration.current;downloadAbort.current?.abort();createPending.current=undefined;setCreateSelection(undefined);setSelecting(false);runtime.current?.cancel();rooms.current?.cancelCreation();creatingRoute.current=false;setCreating(false);setBrowsing(true);if(location.pathname==='/create')history.pushState(null,'','/');requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.directory-title button')?.focus());};
 const startCreateLoad=(file:File,entry:GameLibraryEntry,saved?:SavedCandidate,fresh=false)=>{if(!rooms.current?.beforeSelection()){setSelecting(false);return;}const generation=++createGeneration.current;const current=()=>generation===createGeneration.current&&location.pathname==='/create';createPending.current={file,entry,saved,fresh,current,sawLoading:false};setCreateStatus(`Loading ${entry.label}…`);if(!load(file,current,async fingerprint=>{if(fingerprint.romSha256!==entry.sha256||fingerprint.cartridge.bytes!==entry.size){setCreateStatus('The game bytes changed. Add the NES file again.');return false;}if(saved&&!await candidateStillStored(saved,fingerprint)){setCreateStatus('This saved game changed or was deleted. Add the NES file again.');return false;}return true;})){createPending.current=undefined;setSelecting(false);}};
 const selectCreate=async(entry:GameLibraryEntry)=>{if(!rooms.current?.beforeSelection())return;const generation=++createGeneration.current;downloadAbort.current?.abort();createPending.current=undefined;setClaimFailed(false);setSelecting(true);setPersistenceMessage('');setCreateStatus(`Checking ${entry.label}…`);try{let file:File,saved:SavedCandidate|undefined;if(entry.kind==='saved'){saved=await savedCandidate(entry.sha256);file=saved.file;}else{if(!catalogAvailability[entry.catalogId])throw Error('This included game is unavailable here.');const abort=new AbortController();downloadAbort.current=abort;file=await downloadCatalogEntry(catalogEntry(entry.catalogId),abort.signal,bytes=>{if(generation===createGeneration.current)setCreateStatus(`Downloading ${entry.label}… ${Math.ceil(bytes/1024)} KiB`);});}if(generation!==createGeneration.current||location.pathname!=='/create')return;startCreateLoad(file,entry,saved);}catch(error){if(generation===createGeneration.current){setSelecting(false);if(createSelection?.entry.sha256===entry.sha256){++selectionGeneration.current;setCreateSelection(undefined);}setCreateStatus(error instanceof Error?error.message:'Could not load this game. Retry or add a file.');requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.create-library-title button')?.focus());}}};
 const addCreate=(file:File)=>{if(!rooms.current?.beforeSelection())return;const generation=++createGeneration.current;downloadAbort.current?.abort();createPending.current=undefined;setClaimFailed(false);setSelecting(true);setPersistenceMessage('');setCreateStatus('Checking the NES file…');void file.arrayBuffer().then(bytes=>crypto.subtle.digest('SHA-256',bytes)).then(async hash=>{if(generation!==createGeneration.current)return;const sha256=Array.from(new Uint8Array(hash),byte=>byte.toString(16).padStart(2,'0')).join('');const entries=await gameLibrary().catch(()=>[]);const found=entries.find(row=>row.sha256===sha256);const entry:GameLibraryEntry=found??{kind:'saved',sha256,size:file.size,label:file.name.replace(/[\p{C}]/gu,'').trim().slice(0,80)||'NES game',source:'import',lastUsedAt:Date.now()};if(generation===createGeneration.current)startCreateLoad(file,entry,undefined,true);}).catch(()=>{if(generation===createGeneration.current){setSelecting(false);setCreateStatus('Could not read this file. Choose it again.');requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.create-library-title button')?.focus());}});};
 const createRoom=async()=>{const selected=createSelection;if(selecting||!selected||!selected.current()||!runtime.current?.isLoaded(selected.fingerprint)){setCreateStatus('The selected game changed. Select it again.');return;}setClaimFailed(false);setCreateStatus('Checking selected game…');if(selected.entry.kind==='saved'&&!selected.fresh){try{const candidate=await savedCandidate(selected.entry.sha256);if(!await candidateStillStored(candidate,selected.fingerprint)){setCreateSelection(undefined);setCreateStatus('This saved game changed or was deleted. Add the NES file again.');return;}}catch{setCreateSelection(undefined);setCreateStatus('This saved game changed or was deleted. Add the NES file again.');return;}}if(!selected.current()||!runtime.current?.isLoaded(selected.fingerprint))return;if(selected.entry.kind==='included'){const includedId=selected.entry.catalogId;const offer=roomState.directory?.find(room=>room.catalogId===includedId&&room.occupancy===0&&room.status==='waiting'&&!!room.code);if(!offer?.code){setCreateStatus('No Host place is available. Retry when an offer appears.');return;}try{await rooms.current?.createIncluded(offer.code,selected.fingerprint,visibility);}catch(error){if(selected.current()){setClaimFailed(true);setCreateStatus(`${error instanceof Error?error.message:'Could not claim Host.'} Retry Create room or choose another game.`);}}}else await rooms.current?.createCustom(selected.file,selected.fingerprint,visibility,selected.current);};
 const roomStartRequired=!!roomView&&!roomView.started;
 const [muted,setMuted] = useState(true), [drag,setDrag] = useState(false);
 const preferencesIdentity=state.fingerprint ? fileIdentity(state.fingerprint) : undefined;
 const preferences=usePreferences(preferencesIdentity,value=>{setControls(value.controls);runtime.current?.configureControls(value.controls);setFilter(value.filter);setVolume(value.volume);runtime.current?.setVolume(value.volume);});
 const openLocalData=(fromSettings=false,focus:'heading'|'voice'='heading')=>openTool('localData',fromSettings);
 const batteryAction=async(action:()=>Promise<void>)=>{try{await action();setPersistenceMessage('');}catch(error){setPersistenceMessage(error instanceof Error ? error.message : 'Battery operation failed.');}};

 useEffect(() => { const player = new LocalPlayer(canvas.current!,setState); runtime.current = player; return () => { player.dispose(); runtime.current = null; }; },[]);
 const choose = () => { picker.current!.value = ''; picker.current!.click(); };
 const invitationRequested=new URLSearchParams(invitationHash.slice(1)).has('invite');
 useEffect(()=>{if(!roomState.releaseNotice)return;setTool(null);if(document.fullscreenElement===panel.current){void document.exitFullscreen().then(()=>setFullscreenIssue('')).catch(()=>setFullscreenIssue(state.loaded?'Could not exit fullscreen. Resume your local game here, or press Esc to leave fullscreen.':'Could not exit fullscreen. Press Esc, then choose View rooms.'));}},[roomState.releaseNotice]);
 useLayoutEffect(()=>{if(!roomState.releaseNotice)return;const selector=fullscreen?'.fullscreen-release button':'.release-notice button';document.querySelector<HTMLElement>(selector)?.focus();},[roomState.releaseNotice,fullscreen]);
 const recoverFullscreenRelease=async()=>{if(!state.loaded&&document.fullscreenElement){try{await document.exitFullscreen();}catch{setFullscreenIssue('Could not exit fullscreen. Press Esc, then choose View rooms.');return;}}setFullscreenIssue('');rooms.current?.recoverRelease();};
 const showDiscovery=!creating&&(browsing||(!roomView&&(invitationRequested||!state.loaded))),showRoom=!!roomView&&!roomView.started&&!browsing&&!creating,known=state.fingerprint?catalogId(state.fingerprint):undefined;
 const inviting=showDiscovery&&!roomView&&invitationRequested;
 const playControls=<PlayControls controls={controls} room={roomView} edit={()=>void openTool('settings')} sessionControllers={()=>{const disclosure=document.querySelector<HTMLDetailsElement>('.controller-disclosure');if(disclosure){disclosure.open=true;disclosure.querySelector<HTMLElement>('summary')?.focus();}}}/>;
 return <main className={`${creating?'creating':showDiscovery?'discovery':showRoom?'waiting-room':'playing'}${browsing?' browsing':''}${inviting?' inviting':''}${state.shared?' shared-session':''}${roomView?.started?' with-room':''}${tool?' tooling':''}${roomState.releaseNotice?' released':''}`} data-coordinator={clientConfig.coordinatorUrl}>
  <header><span className="brand">RETRO COOP</span><span data-testid="guest">{guest}</span>{tool?<button onClick={backTool}>Back</button>:<>{!creating&&!inviting&&(roomView||state.loaded)&&<button onClick={()=>setBrowsing(value=>!value)}>{browsing?roomView?'Return to room':'Resume local game':'Public rooms'}</button>}<button data-settings onClick={()=>openTool('settings')}>Settings</button></>}</header>
  <input ref={picker} type="file" accept=".nes" hidden aria-label="NES cartridge file" onChange={event => {const file=event.target.files?.[0];if(file){if(creating)addCreate(file);else load(file);}}}/>
  {creating&&<CreateGame selected={createSelection} loading={state.loading||selecting} busy={roomState.busy} status={roomState.busy||roomState.hostFailure?roomState.status:createStatus} claimFailed={claimFailed} persistenceMessage={persistenceMessage} libraryRevision={libraryRevision} visibility={visibility} setVisibility={setVisibility} policy={policy} setPolicy={changePolicy} offers={roomState.directory??[]} onSelect={entry=>void selectCreate(entry)} onAdd={()=>{if(rooms.current?.beforeSelection()){setCreateStatus('Choose a NES file, or retry Create room.');choose();}}} onDrop={file=>file?addCreate(file):(rooms.current?.beforeSelection(),setCreateStatus('Add one NES file at a time.'))} onCreate={()=>void createRoom()} onBack={leaveCreate} onCancel={()=>{if(roomState.busy){rooms.current?.cancelCreation();setCreateStatus('Room creation cancelled. Retry when ready.');}else{++createGeneration.current;downloadAbort.current?.abort();createPending.current=undefined;setSelecting(false);runtime.current?.cancel();setCreateStatus('Cancelled. Select a game to retry.');}}} onLocal={()=>{creatingRoute.current=false;setCreating(false);setBrowsing(false);if(location.pathname==='/create')history.pushState(null,'','/');}}/>}
  <section ref={panel} className={`panel ${drag ? 'drag' : ''}`} aria-labelledby="player-title" onDragOver={event => {event.preventDefault(); setDrag(true);}} onDragLeave={event => {if(!event.currentTarget.contains(event.relatedTarget as Node)) setDrag(false);}} onDrop={event => {event.preventDefault();setDrag(false);if(event.dataTransfer.files.length === 1) load(event.dataTransfer.files[0]); else runtime.current?.rejectSelection('Choose one NES cartridge at a time. Your previous game is preserved.');}}>
   {roomState.releaseNotice&&fullscreen&&<div className="release-notice fullscreen-release" role="alert"><p>{roomState.releaseNotice}</p>{fullscreenIssue&&<p role="status">{fullscreenIssue}</p>}<button onClick={()=>void recoverFullscreenRelease()}>{state.loaded?'Resume local game':'View rooms'}</button></div>}
   <div className={`screen ${filter}`}><canvas ref={canvas} width="256" height="240" tabIndex={0} aria-label="Local game screen"/>{!state.loaded && <p>YOUR NEXT ADVENTURE<br/><span>starts with a file</span></p>}</div>
   <div className="player-info"><p className="eyebrow">{state.shared?'Shared play · your controller':'Local practice · your controls'}</p><h2 id="player-title">{state.shared ? (state.running?'Playing together':'Shared game paused') : state.loaded ? 'Your local game' : 'Drop your NES game here'}</h2>
   <p>{state.shared ? 'The game runs in your browser. Saves keep a local copy of your progress.' : state.loaded ? 'Your local game stays available if the room service cannot connect.' : 'Choose a file, or drop it anywhere in this panel. Hosting uploads its bytes to the room server.'}</p>
   {state.loading&&<div className="controls"><button onClick={() => {runtime.current?.cancel();rooms.current?.cancelCreation();}}>Cancel loading</button></div>}
   {state.loaded&&<><div className="controls">{!roomStartRequired&&(!state.shared||state.running)&&<button disabled={state.loading} onClick={() => state.running ? runtime.current?.pause() : runtime.current?.resume() && rooms.current?.localPlayIntent()}>{state.running ? 'Pause' : 'Resume'}</button>}<button aria-pressed={muted} onClick={() => {const value = !muted;setMuted(value);runtime.current?.setMuted(value);}}>{muted ? 'Unmute' : 'Mute'}</button></div>
   <div className="controls"><button onClick={()=>openTool('saves')}>Saves</button>{!state.shared&&<button onClick={()=>openTool('rewind')}>Rewind</button>}<button onClick={()=>openTool('help')}>Game help</button><button onClick={()=>void toggleFullscreen()}>{fullscreen ? 'Exit fullscreen' : 'Fullscreen'}</button></div></>}
   {fullscreen && <p className="hint">Press Esc or Exit fullscreen to return.</p>}{fullscreenIssue && <p role="status">{fullscreenIssue}</p>}
   {state.inputIssue && <p role="alert">{state.inputIssue} <button onClick={()=>{changeControls({...controls,device:null});runtime.current?.useKeyboard();}}>Use keyboard</button></p>}
   <p role="status" data-testid="player-status" aria-live="polite">{state.status}</p>{state.audioIssue && <p className="hint" role="status">{state.audioIssue} <button onClick={() => runtime.current?.retryAudio()}>Retry sound</button></p>}
   <p className="hint">Uncompressed iNES / NES 2.0 cartridges. Support varies by cartridge hardware and available memory. Archives and disk images cannot load.</p>
   <p className="hint">Experimental compatibility: a loaded game is not a guarantee that every mapper feature works.</p>
   <span aria-label="Rendered frames" data-testid="frames">{state.frames} frames</span>
   {(state.storageIssue || preferences.issue || persistenceMessage) && <p role="status" data-testid="persistence-status">{state.storageIssue || preferences.issue || persistenceMessage} <button onClick={()=>openLocalData()}>Manage local data</button></p>}
   {state.batteryAvailable && <div className="battery-actions"><button onClick={()=>void batteryAction(async()=>{downloadSave(await runtime.current!.exportBattery(),undefined,'battery');})}>Export current battery</button>{state.storageIssue&&<button onClick={()=>void batteryAction(()=>runtime.current!.retryBatteryPersistence())}>Retry battery saving</button>}</div>}
   </div>
  </section>
  <RoomPanel playCards={roomView?.started&&!tool?<>{playControls}{roomView.started!=='solo'&&<VoiceControls compact onSettings={()=>void openTool('settings',false,'voice')} talkBinding={controls[controls.device?'gamepad':'keyboard'].pushToTalk.map(bindingLabel).join(' / ')||'Unbound'} state={voice} voice={rooms.current?.voice()}/>}</>:undefined} renderFps={state.running?state.renderFps:undefined} showDiscovery={showDiscovery} releaseInFullscreen={fullscreen} onChoose={choose} onCreate={enterCreate} onBrowse={()=>setBrowsing(true)} onInvitationDismiss={()=>setInvitationHash('')} onAcquired={load} selectionLoading={state.loading} ref={rooms} controls={controls} onVoice={setVoice} player={()=>runtime.current} fingerprint={state.fingerprint} onNickname={setGuest} policy={policy} changePolicy={changePolicy} onConnection={setConnection} onRoomChange={syncRoom} onState={setRoomState}/>
  {state.loaded&&!roomView?.started&&!tool&&<aside className="solo-controls">{playControls}</aside>}
  <LocalData open={tool==='localData'} player={runtime.current} preferencesIdentity={preferencesIdentity} beforeClear={()=>{runtime.current?.stopPersistence();preferences.stop();}} afterClear={()=>{preferences.dismiss();setPersistenceMessage('Local data deleted. Current progress remains in memory.');}}/>
  <Rewind open={tool==='rewind' && state.loaded && !state.loading && !state.shared} player={runtime.current}/>
  <Saves open={tool==='saves' && state.loaded && !state.loading} player={runtime.current} shared={!!state.shared} game={`${state.fingerprint?.romSha256}:${state.fingerprint?.coreSha256}`}/>
  <Settings voice={<VoiceControls state={voice} voice={rooms.current?.voice()}/>} localData={()=>openLocalData(true)} connection={<><ConnectionPolicyControl policy={policy} change={changePolicy}/><p>{connection}</p></>} open={tool==='settings'} controls={controls} change={changeControls} filter={filter} setFilter={value=>{setFilter(value);preferences.remember({controls,filter:value,volume});}} volume={volume} setVolume={value=>{setVolume(value);runtime.current?.setVolume(value);preferences.remember({controls,filter,volume:value});}} muted={muted} audioIssue={state.audioIssue} audioState={state.audioState} retryAudio={()=>runtime.current?.retryAudio()}/>
  {tool==='help'&&<section className="settings game-help tool-page" aria-labelledby="game-help-title"><h2 id="game-help-title" tabIndex={-1}>Game help{known?` · ${catalogEntry(known).title}`:''}</h2><p>{known?catalogEntry(known).instructions:'Game-specific instructions are not available for this file.'}</p><p>Focus the game screen to control it. The Your controls card beside the game shows your current bindings. Use Edit controls to remap them in Settings. Play continues when you switch tabs.</p><p>{known?catalogEntry(known).credits:'This local file was supplied by the player; consult its creator for game-specific instructions and credits.'}</p>{known&&<p>{catalogEntry(known).license}</p>}{state.fingerprint&&<details><summary>Technical details</summary><dl data-testid="fingerprint"><dt>Cartridge</dt><dd>{state.fingerprint.cartridge.format} · mapper {state.fingerprint.cartridge.mapper} / {state.fingerprint.cartridge.submapper} · {state.fingerprint.cartridge.region} · {state.fingerprint.cartridge.bytes} bytes</dd><dt>Exact file SHA-256</dt><dd>{state.fingerprint.romSha256}</dd><dt>Emulator build SHA-256</dt><dd>{state.fingerprint.coreSha256}</dd><dt>Local settings (schema {state.fingerprint.localSchema})</dt><dd>{state.fingerprint.settings}</dd></dl></details>}</section>}
  <footer>Your game runs in this browser. Hosting a custom room uploads its game file to the room server while the room is open. Room details, connection signaling and temporary chat also go to the service. Optional voice goes to the other player through the peer connection.</footer>
 </main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
