import React,{useEffect,useRef,useState} from 'react';
import {catalog} from '../../../packages/contracts/src/catalog.ts';
import type {RoomView,Fingerprint} from '../../../packages/contracts/src/rooms.ts';
import type {RoomSlot} from '../../../packages/contracts/src/slots.ts';
import {validChatText} from '../../../packages/contracts/src/chat.ts';
import type {ChatState} from './chat-client.ts';
import type {RoomClient} from './room-client.ts';
import {RoomSlots} from './RoomSlots.tsx';
import {PlayingTools} from './PlayingTools.tsx';
import type {Controls} from './controls.ts';
import {libraryEntries,verifiedSavedFile,type LibraryEntry} from './rom-library.ts';

type Panel='identity'|'voice'|'settings'|'lobby'|null;
export function UnifiedChat({state,connected,onDraft,onSend,onDiscard}:{state:ChatState;connected:boolean;onDraft:(text:string)=>void;onSend:()=>void;onDiscard:()=>void}){
 const log=useRef<HTMLOListElement>(null),following=useRef(true);
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{if(following.current&&log.current)log.current.scrollTop=log.current.scrollHeight;},[state.messages.at(-1)?.id]);
 useEffect(()=>{const retryAt=state.outbox?.retryAt;if(!retryAt)return;const timer=window.setTimeout(()=>setNow(Date.now()),Math.max(0,retryAt-Date.now())+10);return()=>window.clearTimeout(timer);},[state.outbox?.retryAt]);
 return <section className="rc-chat" aria-label="Lobby chat"><div className="rc-section-head"><span className="rc-eyebrow">CHAT</span><small role={state.outbox?.error?'status':undefined} title={state.outbox?.error}>{state.outbox?.error?'Message not sent. Retry or Discard.':connected?'':'Reconnecting…'}</small></div><ol className="rc-chat-history" ref={log} role="log" aria-label="Lobby messages" onScroll={()=>{const node=log.current;if(node)following.current=node.scrollHeight-node.scrollTop-node.clientHeight<20;}}>{state.messages.map(message=><li key={message.id}><strong>{state.ownClientIds.includes(message.clientId)?'(you) ':''}{message.nickname}:</strong> {message.text}</li>)}</ol><form onSubmit={event=>{event.preventDefault();if(validChatText(state.draft)&&!state.sending)onSend();}}><input aria-label="Message everyone" placeholder="Message everyone" value={state.draft} readOnly={!!state.outbox} onChange={event=>onDraft(event.target.value)} maxLength={500}/>{state.outbox&&!state.sending?<span className="rc-chat-recovery"><button type="button" disabled={!connected||!!state.outbox.retryAt&&now<state.outbox.retryAt} onClick={onSend}>Retry</button><button type="button" onClick={onDiscard}>Discard</button></span>:<button type="submit" disabled={!connected||!validChatText(state.draft)||state.sending}>Send</button>}</form></section>;
}

export function SessionStage({room,chat,connected,canvas,canvasLoaded,gameTitle,previewImage,scanlines=false,side,onSide,onAct,onKick,onSlotFeedback,onSlotInspect,onChoose,onIncluded,onSaved,onRetryMember,onDraft,onSend,onDiscard,onCancelSelection,loadingLabel,sideContent,local=false,compactUtilities=false,selectionAllowed=true,controls,muted,volume,onMute,onVolume,onConfigure,onVoiceSettings}:{
 room?:RoomView;chat?:ChatState;connected:boolean;canvas:React.ReactNode;canvasLoaded:boolean;gameTitle?:string;previewImage?:string;scanlines?:boolean;side:Panel;onSide:(side:Panel)=>void;onAct:RoomClient['act'];onKick:(slot:RoomSlot)=>void;onSlotFeedback:(message:string)=>void;onSlotInspect:(name:string)=>void;onChoose:()=>void;onIncluded:(id:(typeof catalog)[number]['id'])=>void;onSaved:(file:File)=>boolean;onRetryMember:()=>void;onDraft:(text:string)=>void;onSend:()=>void;onDiscard:()=>void;onCancelSelection:()=>void;loadingLabel?:string;sideContent?:React.ReactNode;local?:boolean;compactUtilities?:boolean;selectionAllowed?:boolean;controls:Controls;muted:boolean;volume:number;onMute:()=>void;onVolume:(value:number)=>void;onConfigure:()=>void;onVoiceSettings:()=>void;
}){
 const [picker,setPicker]=React.useState(false);
 const [gameExpanded,setGameExpanded]=React.useState(false);
 const [pickerPage,setPickerPage]=React.useState<'choices'|'saved'>('choices'),[saved,setSaved]=React.useState<LibraryEntry[]>([]),[savedIndex,setSavedIndex]=React.useState(0),[savedStatus,setSavedStatus]=React.useState(''),[savedBusy,setSavedBusy]=React.useState(false);
 const savedRequest=useRef(0),pickerOpen=useRef(false);
 const contextKey=`${room?.id??'local'}:${room?.fingerprint?.romSha256??''}:${local}:${selectionAllowed}`;
 const liveContext=useRef(contextKey);
 liveContext.current=contextKey;
 const closePicker=()=>{++savedRequest.current;pickerOpen.current=false;setPicker(false);setSavedBusy(false);setSavedStatus('');};
 const showPicker=()=>{++savedRequest.current;pickerOpen.current=true;setSavedBusy(false);setSavedStatus('');setPicker(true);};
 useEffect(()=>{closePicker();setPickerPage('choices');},[contextKey]);
 useEffect(()=>()=>{++savedRequest.current;pickerOpen.current=false;},[]);
 useEffect(()=>{setGameExpanded(false);},[room?.id,room?.started,local]);
 useEffect(()=>{if(!gameExpanded)return;const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setGameExpanded(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[gameExpanded]);
 useEffect(()=>{if(side)closePicker();},[side]);
 const openSaved=()=>{const request=++savedRequest.current,context=contextKey;setPickerPage('saved');setSavedIndex(0);setSavedStatus('Checking saved games…');void libraryEntries().then(rows=>{if(request!==savedRequest.current||!pickerOpen.current||context!==liveContext.current)return;const stored=rows.filter(row=>!catalog.some(entry=>entry.sha256===row.sha256));setSaved(stored);setSavedStatus(stored.length?'':'No saved games yet. Add a NES file instead.');}).catch(()=>{if(request===savedRequest.current&&pickerOpen.current&&context===liveContext.current)setSavedStatus('Saved games are unavailable. Add a NES file instead.');});};
 const chooseSaved=async(item:LibraryEntry)=>{const request=++savedRequest.current,context=contextKey;setSavedBusy(true);setSavedStatus(`Checking ${item.label}…`);const current=()=>request===savedRequest.current&&pickerOpen.current&&context===liveContext.current;try{const file=await verifiedSavedFile(item.sha256);if(!current())return;if(onSaved(file)){closePicker();}else setSavedStatus('Could not load the saved game. Try again.');}catch(error){if(current())setSavedStatus(error instanceof Error?error.message:'Could not load the saved game.');}finally{if(current())setSavedBusy(false);}};
 const playing=!!room?.started||local;
 const gameName=room?.gameTitle??gameTitle;
 const previewBase=import.meta.env.BASE_URL;
 const image=previewImage??(room?.catalogId==='super-tilt-bro-pal'?`${previewBase}previews/super-tilt.png`:room?.catalogId==='from-below-1.0'?`${previewBase}previews/from-below.png`:undefined);
 const savedPages=Math.max(1,Math.ceil(saved.length/3));
 const pickerContents=pickerPage==='choices'?<><strong>Choose a NES game</strong><div>{catalog.map(entry=><button key={entry.id} onClick={()=>{closePicker();onIncluded(entry.id);}}>{entry.title}</button>)}<button onClick={openSaved}>Saved games</button><button onClick={()=>{closePicker();onChoose();}}>Add NES file</button></div><button className="rc-quiet" onClick={closePicker}>Cancel</button></>:<><strong>Saved games</strong><div className="rc-saved-list">{saved.slice(savedIndex*3,savedIndex*3+3).map(item=><button key={item.sha256} disabled={savedBusy} title={item.label} onClick={()=>void chooseSaved(item)}>{item.label}</button>)}</div><small className="rc-saved-status" role="status">{savedStatus}</small><div className="rc-saved-pages"><button disabled={savedIndex===0} onClick={()=>setSavedIndex(savedIndex-1)}>‹</button><span>{savedIndex+1}/{savedPages}</span><button disabled={savedIndex>=savedPages-1} onClick={()=>setSavedIndex(savedIndex+1)}>›</button></div><button className="rc-quiet" onClick={()=>{++savedRequest.current;setSavedBusy(false);setPickerPage('choices');}}>Back to games</button></>;
 const progressContents=loadingLabel?<div className="rc-game-progress" role="status"><strong>{loadingLabel}</strong><small>{room?'The lobby stays open while the game is prepared.':'The game will open when it is ready.'}</small><button className="rc-quiet" onClick={onCancelSelection}>Cancel selection</button></div>:null;
 return <div className={`rc-session${playing?' rc-session-playing':''}${room?.started?' rc-shared-playing':''}${local?' rc-local-session':''}${side&&!room?.started?' rc-has-side':''}${picker?' rc-has-picker':''}`}>
  {room&&<section className="rc-players"><div className="rc-section-head"><span className="rc-eyebrow">PLAYERS</span><small>{room.occupancy}/5</small></div><RoomSlots room={room} connected={connected} act={onAct} onKickRequested={onKick} onFeedback={onSlotFeedback} onInspect={onSlotInspect}/></section>}
  <section className={`rc-game-zone${side&&!room?.started?' rc-with-side':''}`}><div className="rc-game-main"><div className="rc-section-head rc-game-toolbar"><strong className="rc-game-heading" title={gameName??(playing?'Now playing':'NES game')}>{gameName??(playing?'Now playing':'NES game')}</strong><div className="rc-game-links">{room?.role==='host'&&!room.started&&room.fingerprint&&<button className="rc-direct-action" onClick={()=>{onSide(null);showPicker();}}>Change game</button>}{room?.fingerprint&&room.role!=='host'&&!canvasLoaded&&!room.started&&<button className="rc-direct-action" onClick={()=>room.catalogId?onIncluded(room.catalogId):onRetryMember()}>Retry game</button>}</div></div>
   <div className={`rc-game-display${playing?' rc-live':''}${scanlines?' rc-scanlines':''}${gameExpanded?' rc-game-fullscreen':''}`} role={playing&&canvasLoaded?'button':undefined} tabIndex={playing&&canvasLoaded?0:undefined} aria-label={playing&&canvasLoaded?gameExpanded?'Return game to lobby':'Expand game to full screen':undefined} onClick={playing&&canvasLoaded?()=>setGameExpanded(value=>!value):undefined} onKeyDown={event=>{if(event.target===event.currentTarget&&['Enter',' '].includes(event.key)&&playing&&canvasLoaded){event.preventDefault();setGameExpanded(value=>!value);}}}><div className="rc-canvas-host" hidden={!playing||local&&!canvasLoaded}>{canvas}</div>{playing?local&&!canvasLoaded?progressContents??<button className="rc-load-game" onClick={onChoose}><b aria-hidden="true">＋</b><strong>Load NES game</strong><small>Choose a file from this device</small></button>:!canvasLoaded&&<span>Choose a NES game to play.</span>:picker?<><div className="rc-game-picker rc-desktop-picker">{pickerContents}</div><div className="rc-picker-cue">Choose a game on the right</div></>:room?.role==='host'&&progressContents?progressContents:room?.fingerprint?<div className="rc-preview"><div className="rc-preview-media">{image?<img src={image} alt={`Preview of ${gameName}`} loading="eager"/>:<div className="rc-preview-placeholder">{canvasLoaded?'Preview unavailable':'Preview loads with the game'}</div>}</div></div>:room?.role==='host'?<button className="rc-load-game" onClick={()=>{onSide(null);showPicker();}}><b aria-hidden="true">＋</b><strong>Load NES game</strong><small>Choose one while players join</small></button>:<div className="rc-wait-game">Waiting for the host to load a NES game</div>}</div>
  </div><aside className="rc-side-panel" aria-label={side?`${side} panel`:undefined}>{side&&!room?.started&&!compactUtilities&&<div className="rc-side-content">{sideContent}</div>}</aside></section>
  <aside className="rc-mobile-side-panel" hidden={!side||!!room?.started} aria-label={side?`${side} panel`:undefined}>{side&&!room?.started&&compactUtilities&&<div className="rc-side-content">{sideContent}</div>}</aside>
  <aside className="rc-mobile-picker-panel" hidden={!picker} aria-label="Choose a NES game"><div className="rc-game-picker">{pickerContents}</div></aside>
  {room?.started&&<aside className="rc-play-tools rc-playing-menu" aria-label="Game menu"><div className="rc-side-content">{sideContent}</div></aside>}
  {room&&chat&&<UnifiedChat state={chat} connected={connected} onDraft={onDraft} onSend={onSend} onDiscard={onDiscard}/>}
 </div>;
}
