import React,{useEffect,useRef,useState} from 'react';
import {catalog} from '../../../packages/contracts/src/catalog.ts';
import type {RoomView,Fingerprint} from '../../../packages/contracts/src/rooms.ts';
import type {RoomSlot} from '../../../packages/contracts/src/slots.ts';
import {validChatText} from '../../../packages/contracts/src/chat.ts';
import type {ChatState} from './chat-client.ts';
import type {RoomClient} from './room-client.ts';
import {Controller} from './Controller.tsx';
import type {Controls} from './controls.ts';
import {RoomSlots} from './RoomSlots.tsx';
import {libraryEntries,verifiedSavedFile,type LibraryEntry} from './rom-library.ts';

const phoneLayoutQuery='(max-width:650px), (max-width:1000px) and (max-height:500px)';
type Panel='identity'|'voice'|'settings'|'lobby'|null;
function GameTitle({title}:{title:string}){
 const windowRef=useRef<HTMLElement>(null),textRef=useRef<HTMLSpanElement>(null);
 const [distance,setDistance]=useState(0);
 useEffect(()=>{
  const viewport=windowRef.current,text=textRef.current;if(!viewport||!text)return;
  const measure=()=>setDistance(text.getBoundingClientRect().width>viewport.clientWidth+1?text.getBoundingClientRect().width+32:0);
  const observer=new ResizeObserver(measure);observer.observe(viewport);observer.observe(text);measure();
  return()=>observer.disconnect();
 },[title]);
 return <strong ref={windowRef} className="rc-game-heading" title={title} tabIndex={distance?0:undefined} data-overflow={distance>0} style={{'--rc-title-distance':`${distance}px`,'--rc-title-duration':`${distance/32}s`} as React.CSSProperties}><span className="rc-title-track"><span ref={textRef} className="rc-title-text">{title}</span>{distance>0&&<span aria-hidden="true">{title}</span>}</span></strong>;
}

export function UnifiedChat({state,connected,onDraft,onSend,onDiscard}:{state:ChatState;connected:boolean;onDraft:(text:string)=>void;onSend:()=>void;onDiscard:()=>void}){
 const log=useRef<HTMLOListElement>(null),following=useRef(true);
 const [now,setNow]=useState(Date.now());
 const feedback=state.outbox?.error?'Message not sent.':connected?'':'Reconnecting…';
 useEffect(()=>{if(following.current&&log.current)log.current.scrollTop=log.current.scrollHeight;},[state.messages.at(-1)?.id,feedback]);
 useEffect(()=>{const retryAt=state.outbox?.retryAt;if(!retryAt)return;const timer=window.setTimeout(()=>setNow(Date.now()),Math.max(0,retryAt-Date.now())+10);return()=>window.clearTimeout(timer);},[state.outbox?.retryAt]);
 return <section className="rc-chat" aria-label="Lobby chat"><div className="rc-section-head"><span className="rc-eyebrow">CHAT</span></div><ol className="rc-chat-history" ref={log} role="log" aria-label="Lobby messages" tabIndex={0} onScroll={()=>{const node=log.current;if(node)following.current=node.scrollHeight-node.scrollTop-node.clientHeight<20;}}>{state.messages.map(message=><li key={message.id}><strong>{state.ownClientIds.includes(message.clientId)?'(you) ':''}{message.nickname}:</strong> {message.text}</li>)}{feedback&&<li className="rc-chat-feedback" role="status" title={state.outbox?.error}>{feedback}</li>}</ol><form onSubmit={event=>{event.preventDefault();if(validChatText(state.draft)&&!state.sending)onSend();}}><input aria-label="Message everyone" placeholder="Message everyone" value={state.draft} readOnly={!!state.outbox} onChange={event=>onDraft(event.target.value)} maxLength={500}/>{state.outbox&&!state.sending?<span className="rc-chat-recovery"><button type="button" disabled={!connected||!!state.outbox.retryAt&&now<state.outbox.retryAt} onClick={onSend}>Retry</button><button type="button" onClick={onDiscard}>Discard</button></span>:<button type="submit" disabled={!connected||!validChatText(state.draft)||state.sending}>Send</button>}</form></section>;
}

export function SessionStage({loadedGameIdentity,controls,controllerEnabled,controllerEditRequest,onControllerMask,onControlsChange,onControllerEditing,controllerEditorHost,onRequestControllerEdit,onCancelControllerEdit,storageIssue,room,chat,connected,canvas,canvasLoaded,playReady,gameTitle,previewImage,scanlines=false,side,onSide,onAct,onKick,onSlotFeedback,onSlotInspect,onChoose,onIncluded,onSaved,onRetryMember,onDraft,onSend,onDiscard,onCancelSelection,selectionFinishing=false,selectionUncertain=false,onRetrySelection,loadingLabel,sideContent,local=false,selectionAllowed=true}:{
 loadedGameIdentity?:string;controls:Controls;controllerEnabled:boolean;controllerEditRequest:number;onControllerMask:(mask:number)=>void;onControlsChange:(controls:Controls,current:()=>boolean)=>Promise<boolean>;onControllerEditing:(editing:boolean)=>void;controllerEditorHost:React.RefObject<HTMLDivElement|null>;onRequestControllerEdit:()=>void;onCancelControllerEdit:()=>void;storageIssue?:string;
 room?:RoomView;chat?:ChatState;connected:boolean;canvas:React.ReactNode;canvasLoaded:boolean;playReady:boolean;gameTitle?:string;previewImage?:string;scanlines?:boolean;side:Panel;onSide:(side:Panel)=>void;onAct:RoomClient['act'];onKick:(slot:RoomSlot)=>void;onSlotFeedback:(message:string)=>void;onSlotInspect:(name:string)=>void;onChoose:()=>void;onIncluded:(id:(typeof catalog)[number]['id'])=>void;onSaved:(file:File)=>boolean;onRetryMember:()=>void;onDraft:(text:string)=>void;onSend:()=>void;onDiscard:()=>void;onCancelSelection:()=>void;selectionFinishing?:boolean;selectionUncertain?:boolean;onRetrySelection?:()=>void;loadingLabel?:string;sideContent?:React.ReactNode;local?:boolean;selectionAllowed?:boolean;
}){
 const [phone,setPhone]=useState(()=>matchMedia(phoneLayoutQuery).matches);
 const [phonePanel,setPhonePanel]=useState<'game'|'players'|'settings'|'chat'>('game');
 const enteredPlay=useRef(false);
 useEffect(()=>{if(controllerEditRequest){closePicker();if(phone)setPhonePanel('settings');setGameExpanded(false);}},[controllerEditRequest]);
 useEffect(()=>{const query=matchMedia(phoneLayoutQuery),changed=()=>setPhone(query.matches);query.addEventListener('change',changed);return()=>query.removeEventListener('change',changed);},[]);
 const [picker,setPicker]=React.useState(false);
 const [gameExpanded,setGameExpanded]=React.useState(false);
 const [pickerPage,setPickerPage]=React.useState<'choices'|'saved'>('choices'),[saved,setSaved]=React.useState<LibraryEntry[]>([]),[savedIndex,setSavedIndex]=React.useState(0),[savedStatus,setSavedStatus]=React.useState(''),[savedBusy,setSavedBusy]=React.useState(false);
 const savedRequest=useRef(0),pickerOpen=useRef(false);
 const contextKey=`${room?.id??'local'}:${room?.fingerprint?.romSha256??''}:${local}:${selectionAllowed}`;
 const liveContext=useRef(contextKey);
 liveContext.current=contextKey;
 const closePicker=()=>{++savedRequest.current;pickerOpen.current=false;setPicker(false);setSavedBusy(false);setSavedStatus('');};
 const showPicker=()=>{++savedRequest.current;pickerOpen.current=true;setPickerPage('choices');setSavedBusy(false);setSavedStatus('');setPicker(true);};
 useEffect(()=>{closePicker();setPickerPage('choices');},[contextKey]);
 useEffect(()=>()=>{++savedRequest.current;pickerOpen.current=false;},[]);
 useEffect(()=>{enteredPlay.current=false;setGameExpanded(false);setPhonePanel('game');},[room?.id,room?.fingerprint?.romSha256,local]);
 useEffect(()=>{if(!playReady||!canvasLoaded||enteredPlay.current)return;enteredPlay.current=true;if(phone)setGameExpanded(true);},[playReady,canvasLoaded,phone]);
 useEffect(()=>{if(!gameExpanded)return;const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setGameExpanded(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[gameExpanded]);
 useEffect(()=>{if(side)closePicker();},[side]);
 const openSaved=()=>{const request=++savedRequest.current,context=contextKey;setPickerPage('saved');setSavedIndex(0);setSavedStatus('Checking saved games…');void libraryEntries().then(rows=>{if(request!==savedRequest.current||!pickerOpen.current||context!==liveContext.current)return;const stored=rows.filter(row=>!catalog.some(entry=>entry.sha256===row.sha256));setSaved(stored);setSavedStatus(stored.length?'':'No saved games yet. Add a NES file instead.');}).catch(()=>{if(request===savedRequest.current&&pickerOpen.current&&context===liveContext.current)setSavedStatus('Saved games are unavailable. Add a NES file instead.');});};
 const chooseSaved=async(item:LibraryEntry)=>{const request=++savedRequest.current,context=contextKey;setSavedBusy(true);setSavedStatus(`Checking ${item.label}…`);const current=()=>request===savedRequest.current&&pickerOpen.current&&context===liveContext.current;try{const file=await verifiedSavedFile(item.sha256);if(!current())return;if(onSaved(file)){closePicker();}else setSavedStatus('Could not load the saved game. Try again.');}catch(error){if(current())setSavedStatus(error instanceof Error?error.message:'Could not load the saved game.');}finally{if(current())setSavedBusy(false);}};
 const playing=!!room?.started||local;
 const gameName=room?.gameTitle??gameTitle;
 const previewBase=import.meta.env.BASE_URL;
 const image=previewImage??(room?.catalogId==='super-tilt-bro-pal'?`${previewBase}previews/super-tilt.png`:room?.catalogId==='from-below-1.0'?`${previewBase}previews/from-below.png`:undefined);
 const savedPages=Math.max(1,saved.length);
 const pickerContents=pickerPage==='choices'?<><strong>Choose a NES game</strong><div>{catalog.map(entry=><button key={entry.id} onClick={()=>{closePicker();onIncluded(entry.id);}}>{entry.title}</button>)}<button onClick={openSaved}>Saved games</button><button title="NES files or ZIP archives under 2 MB" onClick={()=>{closePicker();onChoose();}}>Add game file</button></div><button className="rc-quiet" onClick={closePicker}>Cancel</button></>:<><strong>Saved games</strong><div className="rc-saved-list">{saved.slice(savedIndex,savedIndex+1).map(item=><button key={item.sha256} disabled={savedBusy} title={item.label} onClick={()=>void chooseSaved(item)}>{item.label}</button>)}</div><small className="rc-saved-status" role="status">{savedStatus}</small><div className="rc-saved-pages"><button className="rc-quiet" onClick={()=>{++savedRequest.current;setSavedBusy(false);setPickerPage('choices');}}>Back to games</button><button aria-label="Previous saved game" disabled={savedIndex===0} onClick={()=>setSavedIndex(savedIndex-1)}>‹</button><span>{savedIndex+1}/{savedPages}</span><button aria-label="Next saved game" disabled={savedIndex>=savedPages-1} onClick={()=>setSavedIndex(savedIndex+1)}>›</button></div></>;
 const progressContents=loadingLabel?<div className="rc-game-progress" role="status"><strong>{loadingLabel}</strong><small>{room?'The lobby stays open while the game is prepared.':'The game will open when it is ready.'}</small><button className="rc-quiet" disabled={selectionFinishing} onClick={selectionUncertain?onRetrySelection:onCancelSelection}>{selectionUncertain?'Retry selection':'Cancel selection'}</button></div>:null;
 return <div data-phone-panel={phonePanel} className={`rc-session${playing?' rc-session-playing':''}${room?.started?' rc-shared-playing':''}${local?' rc-local-session':''}${side&&!room?.started?' rc-has-side':''}${picker?' rc-has-picker':''}`}>
  {room&&<nav className="rc-phone-panels" aria-label="Lobby sections">{(['game','players','settings','chat'] as const).map(panel=><button key={panel} aria-current={phonePanel===panel?'page':undefined} onClick={()=>{if(panel!=='settings')onCancelControllerEdit();setPhonePanel(panel);}}>{panel[0].toUpperCase()+panel.slice(1)}</button>)}</nav>}
  {room&&<section className="rc-players" inert={phone&&phonePanel!=='players'} aria-hidden={phone&&phonePanel!=='players'}><div className="rc-section-head"><span className="rc-eyebrow">PLAYERS</span><small>{room.occupancy}/5</small></div><RoomSlots room={room} connected={connected} act={onAct} onKickRequested={onKick} onFeedback={onSlotFeedback} onInspect={onSlotInspect}/></section>}
  <section onDragOver={event=>{if(selectionAllowed&&(!room||room.role==='host'&&!room.started)){event.preventDefault();event.dataTransfer.dropEffect='copy';}}} onDrop={event=>{event.preventDefault();if(selectionAllowed&&(!room||room.role==='host'&&!room.started)&&event.dataTransfer.files[0]){closePicker();onSaved(event.dataTransfer.files[0]);}}} inert={phone&&phonePanel!=='game'&&!gameExpanded} aria-hidden={phone&&phonePanel!=='game'&&!gameExpanded} className={`rc-game-zone${side&&!room?.started?' rc-with-side':''}`}><div className="rc-game-main"><div inert={picker&&!playing} aria-hidden={picker&&!playing} className="rc-section-head rc-game-toolbar"><GameTitle title={gameName??(playing?'Now playing':'NES game')}/><div className="rc-game-links">{room?.role==='host'&&!room.started&&room.fingerprint&&<button className="rc-direct-action" onClick={()=>{onSide(null);showPicker();}}>Change game</button>}{room?.fingerprint&&room.role!=='host'&&!canvasLoaded&&!room.started&&<button className="rc-direct-action" onClick={()=>room.catalogId?onIncluded(room.catalogId):onRetryMember()}>Retry game</button>}</div></div>
   <div className={`rc-game-display${playing?' rc-live':''}${scanlines?' rc-scanlines':''}${gameExpanded?' rc-game-fullscreen':''}`}>{playing&&canvasLoaded&&<button type="button" className="rc-expansion-action" onClick={event=>{event.stopPropagation();setGameExpanded(value=>!value);}}>{gameExpanded?'Return to lobby view':'Full screen'}</button>}<div inert={picker&&!playing} aria-hidden={picker&&!playing} className="rc-game-viewport" role={playing&&canvasLoaded?'button':undefined} tabIndex={playing&&canvasLoaded?0:undefined} aria-label={playing&&canvasLoaded?gameExpanded?'Return game to lobby':'Expand game to full screen':undefined} onClick={playing&&canvasLoaded?()=>setGameExpanded(value=>!value):undefined} onKeyDown={event=>{if(event.target===event.currentTarget&&['Enter',' '].includes(event.key)&&playing&&canvasLoaded){event.preventDefault();setGameExpanded(value=>!value);}}}><div className="rc-canvas-host" hidden={!playing||local&&!canvasLoaded}>{canvas}</div>{playing?local&&!canvasLoaded?progressContents??<button className="rc-load-game" onClick={onChoose}><b aria-hidden="true">＋</b><strong>Load NES game</strong><small>Choose or drop NES · ZIP under 2 MB</small></button>:!canvasLoaded&&<span>Choose a NES game to play.</span>:room?.role==='host'&&progressContents?progressContents:room?.fingerprint?<div className="rc-preview"><div className="rc-preview-media">{image?<img src={image} alt={`Preview of ${gameName}`} loading="eager"/>:<div className="rc-preview-placeholder">{canvasLoaded?'Preview unavailable':'Preview loads with the game'}</div>}</div></div>:room?.role==='host'?<button className="rc-load-game" onClick={()=>{onSide(null);showPicker();}}><b aria-hidden="true">＋</b><strong>Load NES game</strong><small>Choose or drop NES · ZIP under 2 MB</small></button>:<div className="rc-wait-game">Waiting for the host to load a NES game</div>}</div>{!playing&&picker&&<div className={`rc-game-picker${pickerPage==='saved'?' rc-saved-picker':''}`}>{pickerContents}</div>}<Controller key={`${room?.id??'local'}:${room?.fingerprint?.romSha256??''}:${loadedGameIdentity??''}:${local}`} controls={controls} covered={!playing&&picker} enabled={controllerEnabled&&(!picker||playing)} playing={playing} editRequest={controllerEditRequest} resetKey={`${contextKey}:${room?.slot}:${room?.slots.find(slot=>slot.id===room.slot)?.role}:${room?.game.epoch}:${gameExpanded}:${phonePanel}:${connected}`} onMask={onControllerMask} onChange={onControlsChange} onEditing={onControllerEditing} onRequestEdit={onRequestControllerEdit} phone={phone} editorHost={controllerEditorHost} storageIssue={storageIssue}/></div>
  </div></section>
  <aside className={`rc-session-settings ${room?.started?'rc-playing-menu':'rc-side-panel'}`} inert={phone&&phonePanel!=='settings'} aria-hidden={phone&&phonePanel!=='settings'}><div className="rc-side-content">{sideContent}</div></aside>
  {room&&chat&&<div className="rc-chat-panel" inert={phone&&phonePanel!=='chat'} aria-hidden={phone&&phonePanel!=='chat'}><UnifiedChat state={chat} connected={connected} onDraft={onDraft} onSend={onSend} onDiscard={onDiscard}/></div>}
 </div>;
}
