apiVersion: v1
kind: ResourceQuota
metadata:
  name: retro-coop-staging
spec:
  hard:
    pods: "4"
    services.loadbalancers: "1"
    requests.cpu: "2"
    requests.memory: 4Gi
    requests.ephemeral-storage: 4Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    limits.ephemeral-storage: 6Gi
