apiVersion: v1
kind: Service
metadata:
  name: retro-coop-staging
spec:
  type: LoadBalancer
  loadBalancerClass: networking.gke.io/l4-regional-external
  externalTrafficPolicy: Local
  loadBalancerIP: 192.0.2.1
  loadBalancerSourceRanges:
    - 192.0.2.1/32
  selector:
    app: retro-coop-staging
  ports:
    - name: acme
      protocol: TCP
      port: 80
      targetPort: acme
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
