import argparse, hashlib, json, math, struct, time, wave, os, platform, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts/rooms'))
from ui_helpers import rename_lobby
p=argparse.ArgumentParser();p.add_argument('--role',choices=['host','guest'],required=True);p.add_argument('--lobby',required=True);p.add_argument('--mode',choices=['direct','relay'],required=True);p.add_argument('--output',required=True);a=p.parse_args()
out=Path(a.output);out.mkdir(parents=True,exist_ok=True)
url='https://retro-coop.atobot.cloud/'
tone=out/'voice.wav'
with wave.open(str(tone),'wb') as w:
 w.setparams((1,2,48000,0,'NONE','not compressed'));w.writeframes(b''.join(struct.pack('<h',int(6000*math.sin(2*math.pi*440*i/48000))) for i in range(48000)))
public_ip=urllib.request.urlopen('https://api.ipify.org',timeout=10).read().strip()
started=time.monotonic();result={'public_ip_sha256':hashlib.sha256(public_ip).hexdigest(),'platform':platform.platform(),'github_run_id':os.environ.get('GITHUB_RUN_ID'),'role':a.role,'mode':a.mode,'url':url,'lobby':a.lobby,'page_errors':[]}
with sync_playwright() as pw:
 b=pw.chromium.launch(ignore_default_args=['--mute-audio'],args=['--use-fake-device-for-media-stream',f'--use-file-for-fake-audio-capture={tone.resolve()}'])
 result['browser']=b.version
 c=b.new_context(viewport={'width':1366,'height':768},permissions=['microphone','clipboard-read','clipboard-write']);page=c.new_page();page.set_default_timeout(30000)
 page.on('pageerror',lambda e:result['page_errors'].append(str(e)))
 result['rom_downloads']=[];result['file_chooser_count']=0
 def response(r):
  if r.url.endswith('/rom') and r.request.method=='GET':
   result['rom_downloads'].append({'status':r.status,'sha256':hashlib.sha256(r.body()).hexdigest()})
 page.on('response',response)
 def chooser(_):result['file_chooser_count']+=1
 page.on('filechooser',chooser)
 init=(ROOT/'scripts/gameplay/fixture.js').read_text()+"""
 window.pcs=[];const PC=RTCPeerConnection;window.RTCPeerConnection=class extends PC{constructor(config,...args){super({...config,...(MODE==='relay'?{iceTransportPolicy:'relay'}:{})},...args);pcs.push(this)}};
 const WS=WebSocket;window.WebSocket=class extends WS{constructor(...args){super(...args);this.addEventListener('message',event=>{try{const p=JSON.parse(event.data);if(p.type==='result'&&p.ok&&p.data?.room)proof.room=p.data.room}catch{}})}};
 """.replace('MODE',json.dumps(a.mode))
 page.add_init_script(init)
 def chat(text):
  field=page.get_by_role('textbox',name='Message everyone');field.fill(text);field.press('Enter')
 def marker(text,timeout=120000):
  page.get_by_role('log',name='Lobby messages').get_by_text(text,exact=False).wait_for(timeout=timeout)
 def wait(expr,timeout=60000):page.wait_for_function(expr,timeout=timeout)
 def capture(name):page.screenshot(path=str(out/f'{a.role}-{name}.png'))
 try:
  page.goto(url);page.locator('.rc-listing').wait_for()
  if a.role=='host':
   page.get_by_role('button',name='Host a new game').click();rename_lobby(page,a.lobby)
   # This original diagnostic fixture is generated by the host only.
   import subprocess
   rom=out/'public-diagnostic.nes';subprocess.run([sys.executable,str(ROOT/'spikes/d02/original_fixture.py'),str(rom)],check=True)
   result['rom_sha256']=hashlib.sha256(rom.read_bytes()).hexdigest()
   page.locator('input[aria-label="NES cartridge file"]').set_input_files(str(rom));page.get_by_role('button',name='Change game').wait_for()
   print('HOST_READY '+json.dumps({'lobby':a.lobby,'rom':result['rom_sha256']}),flush=True)
   wait('proof.room?.occupancy===2',480000)
  else:
   def reject_first_download(route):
    page.unroute('**/rooms/*/rom',reject_first_download);route.abort('failed')
   page.route('**/rooms/*/rom',reject_first_download)
   page.get_by_placeholder('Search lobbies').fill(a.lobby)
   page.locator('.rc-lobby-card').filter(has_text=a.lobby).wait_for(timeout=60000);page.locator('.rc-lobby-card').filter(has_text=a.lobby).click()
   wait('proof.room?.role==="member"')
   result['rom_sha256']=page.evaluate('proof.room.fingerprint.romSha256')
   chat('REMOTE GUEST JOINED')
   page.get_by_role('button',name='Retry game',exact=True).wait_for();capture('download-failed')
   result['download_failure_visible']=True
   page.get_by_role('button',name='Retry game',exact=True).click()
  expect(page.get_by_role('button',name='Ready',exact=True)).to_be_enabled(timeout=60000);page.get_by_role('button',name='Ready',exact=True).click()
  if a.role=='host':
   expect(page.get_by_role('button',name='Start →')).to_be_enabled(timeout=60000);page.get_by_role('button',name='Start →').click()
  wait('proof.room?.game?.status==="playing"');page.evaluate('releaseFrames()');wait('proof.frameCount>=10')
  page.get_by_role('button',name='Sound',exact=True).click();page.get_by_role('button',name='Mute game',exact=True).click()
  page.get_by_role('button',name='Voice',exact=True).click();page.get_by_label('Voice mode').select_option('open')
  chat('HOST PLAYING' if a.role=='host' else 'GUEST PLAYING')
  marker('GUEST PLAYING' if a.role=='host' else 'HOST PLAYING')
  energy="async()=>{let n=0;for(const p of pcs)for(const s of(await p.getStats()).values())if(s.type==='inbound-rtp'&&s.kind==='audio')n+=s.totalAudioEnergy||0;return n}"
  e0=page.evaluate(energy);page.wait_for_timeout(1500);result['received_audio_energy']=page.evaluate(energy)-e0
  assert result['received_audio_energy']>1e-5,result
  page.locator('canvas').focus();page.keyboard.down('z' if a.role=='host' else 'c');wait('proof.frameCount>=220');page.keyboard.up('z' if a.role=='host' else 'c')
  result['selected_candidates']=page.evaluate("""async()=>{const all=[];for(const pc of pcs){const s=await pc.getStats();for(const t of s.values())if(t.type==='transport'&&t.selectedCandidatePairId){const p=s.get(t.selectedCandidatePairId),l=s.get(p.localCandidateId),r=s.get(p.remoteCandidateId);all.push({local:l.candidateType,remote:r.candidateType,protocol:l.protocol,roundTripSeconds:p.currentRoundTripTime})}}return all}""")
  assert result['selected_candidates']
  assert all(('relay' in [x['local'],x['remote']])==(a.mode=='relay') for x in result['selected_candidates']),result['selected_candidates']
  capture('playing');chat('HOST SAMPLED' if a.role=='host' else 'GUEST SAMPLED');marker('GUEST SAMPLED' if a.role=='host' else 'HOST SAMPLED')
  if a.role=='host':page.locator('canvas').focus();page.keyboard.press('p')
  wait('proof.room?.game?.status==="paused"');page.evaluate("currentWorker.postMessage({type:'state-hash',requestId:900003})");wait('proof.hashes.length>0');page.wait_for_timeout(200)
  result['paused_hash']=page.evaluate('proof.hashes.at(-1)');result['room_id']=page.evaluate('proof.room.id');result['frames']=page.evaluate('proof.frameCount');capture('paused')
  chat('HOST PAUSED' if a.role=='host' else 'GUEST PAUSED');marker('GUEST PAUSED' if a.role=='host' else 'HOST PAUSED')
  page.locator('canvas').focus();page.keyboard.press('p')
  if a.role=='host':wait('proof.room?.game?.status==="resume_ready"');page.keyboard.press('p')
  wait('proof.room?.game?.status==="playing"');before=page.evaluate('proof.frameCount');page.wait_for_function('n=>proof.frameCount>n+30',arg=before)
  result['resumed']=True;chat('HOST COMPLETE' if a.role=='host' else 'GUEST COMPLETE');marker('GUEST COMPLETE' if a.role=='host' else 'HOST COMPLETE');capture('resumed')
  if a.role=='guest':
   page.get_by_role('button',name='Back to Main Page').click();page.get_by_role('alertdialog').get_by_role('button',name='Leave lobby',exact=True).click();page.locator('.rc-listing').wait_for();result['left']=True
  else:
   wait('proof.room?.occupancy===1');page.get_by_role('button',name='Back to Main Page').click();page.get_by_role('alertdialog').get_by_role('button',name='Close lobby',exact=True).click();page.locator('.rc-listing').wait_for();result['closed']=True
  if a.role=='guest':
   assert result['file_chooser_count']==0
   assert any(r['status']==200 and r['sha256']==result['rom_sha256'] for r in result['rom_downloads']),result['rom_downloads']
  result['result']='pass'
 except Exception as e:
  result['result']='fail';result['error']=str(e);result['body']=page.locator('body').inner_text();capture('failure');raise
 finally:
  try:
   page.set_default_timeout(3000)
   if page.get_by_role('button',name='Back to Main Page').is_visible():
    page.get_by_role('button',name='Back to Main Page').click()
    page.get_by_role('alertdialog').get_by_role('button',name='Close lobby' if a.role=='host' else 'Leave lobby',exact=True).click()
    page.locator('.rc-listing').wait_for()
  except Exception as cleanup_error:result['cleanup_error']=str(cleanup_error)
  result['elapsed_seconds']=round(time.monotonic()-started,2);(out/f'{a.role}.json').write_text(json.dumps(result,indent=2));print(json.dumps(result),flush=True);b.close()
