steps:
  - id: edge
    name: gcr.io/cloud-builders/docker@sha256:001fb4a870a84485cf198c80002f7af42f6456f2dbc261d70a0b5f0111470df4
    args:
      - build
      - --file
      - deploy/staging/Dockerfile
      - --target
      - edge
      - --label
      - org.opencontainers.image.revision=${_SOURCE_REVISION}
      - --tag
      - ${_IMAGE_REPO}/edge:${_SOURCE_REVISION}
      - .
  - id: coordinator
    name: gcr.io/cloud-builders/docker@sha256:001fb4a870a84485cf198c80002f7af42f6456f2dbc261d70a0b5f0111470df4
    args:
      - build
      - --file
      - deploy/staging/Dockerfile
      - --target
      - coordinator
      - --label
      - org.opencontainers.image.revision=${_SOURCE_REVISION}
      - --tag
      - ${_IMAGE_REPO}/coordinator:${_SOURCE_REVISION}
      - .
images:
  - ${_IMAGE_REPO}/edge:${_SOURCE_REVISION}
  - ${_IMAGE_REPO}/coordinator:${_SOURCE_REVISION}
timeout: 1200s
