const raf=requestAnimationFrame.bind(window),cancel=cancelAnimationFrame.bind(window),pending=new Map();let held=true,id=0;
    window.requestAnimationFrame=fn=>held?(pending.set(++id,fn),id):raf(fn);
    window.cancelAnimationFrame=n=>held?pending.delete(n):cancel(n);
    window.releaseFrames=()=>{held=false;for(const fn of pending.values())raf(fn);pending.clear()};
    window.proof={hashes:[],rooms:[],frames:[],frameCount:0,sentHashes:[],timing:{workerMs:0,workerMax:0,frameGaps:[],waitMs:0,waitCount:0,delays:[]}};
    proof.events=[];proof.pacing=[];let epochAt=0,epochFrames=0;
    const note=(kind,detail={})=>{proof.events.push({at:Math.round(performance.now()),kind,...detail});if(proof.events.length>128)proof.events.shift()};
    setInterval(()=>{if(epochAt){proof.pacing.push({at:Math.round(performance.now()-epochAt),frames:epochFrames});if(proof.pacing.length>64)proof.pacing.shift()}},1000);
    proof.admission={lead:{},lateInputs:0,lateInputWaitMs:0,maxInputGapMs:0,hashMs:0,hashMaxMs:0,hashCount:0,nonceRttMs:[]};
    let workerPending=false,lastInputAt=0,hashAt=0;const probes=new Map();
    const observeChannel=channel=>channel.addEventListener('message',({data})=>{let packet;try{packet=JSON.parse(data)}catch{return}const now=performance.now();
      if(packet.type==='transportReply'&&probes.has(packet.nonce)){proof.admission.nonceRttMs.push(now-probes.get(packet.nonce));probes.delete(packet.nonce);}
      if(packet.kind==='input'&&packet.epoch===proof.activeEpoch){const lead=packet.frame-epochFrames;proof.admission.lead[lead]=(proof.admission.lead[lead]||0)+1;if(lastInputAt)proof.admission.maxInputGapMs=Math.max(proof.admission.maxInputGapMs,now-lastInputAt);lastInputAt=now;if(lead===0&&!workerPending&&lastFrame){proof.admission.lateInputs++;proof.admission.lateInputWaitMs+=now-lastFrame;}}
    });
    const P=RTCPeerConnection;window.RTCPeerConnection=class extends P{constructor(...a){super(...a);this.addEventListener('datachannel',({channel})=>observeChannel(channel));for(const event of ['connectionstatechange','iceconnectionstatechange','icegatheringstatechange'])this.addEventListener(event,()=>note(event,{connection:this.connectionState,ice:this.iceConnectionState,gathering:this.iceGatheringState}));}createDataChannel(...a){const channel=super.createDataChannel(...a);observeChannel(channel);return channel;}};
    const ds=RTCDataChannel.prototype.send;RTCDataChannel.prototype.send=function(data){if(typeof data==='string'){let d=JSON.parse(data);if(d.type==='transportProbe')probes.set(d.nonce,performance.now());
      if(d.kind==='input'&&window.gameFault==='drop-input')return;
      if(d.kind==='hash'&&window.gameFault==='bad-hash'){d={...d,hash:'0'.repeat(64)};data=JSON.stringify(d);window.gameFault=undefined;}
      if(d.kind==='input'&&window.gameFault==='old-epoch'){ds.call(this,JSON.stringify({...d,epoch:'obsolete'.repeat(4)}));window.gameFault=undefined;}
      if(d.kind==='input'&&window.gameFault==='future-input'){d={...d,frame:d.frame+121};data=JSON.stringify(d);window.gameFault=undefined;}
      if(d.kind==='input'&&window.gameFault==='duplicate-input'){ds.call(this,data);window.gameFault=undefined;}
      if(d.kind==='hash')proof.sentHashes.push(d);}return ds.call(this,data)};
    let waitStart=0,lastFrame=0,workerStart=0;
    new MutationObserver(()=>{const waiting=document.querySelector('[data-testid=game-status]')?.textContent.includes('Waiting for the other player’s input');if(waiting&&!waitStart){waitStart=performance.now();proof.timing.waitCount++}else if(!waiting&&waitStart){proof.timing.waitMs+=performance.now()-waitStart;waitStart=0}}).observe(document,{subtree:true,childList:true,characterData:true});
    const W=Worker;window.Worker=class extends W{postMessage(data,...rest){if(data.type==='state-hash')hashAt=performance.now();if(data.type==='frame'&&data.epoch){workerStart=performance.now();workerPending=true;}return super.postMessage(data,...rest)}constructor(...a){super(...a);window.currentWorker=this;this.addEventListener('message',event=>{const {data}=event;
// Diagnostic delivery delay leaves the native frame and its inputs unchanged.
if(data.type==='frame'&&data.epoch&&window.workerFloorMs&&!event.floorDelivered){const remaining=window.workerFloorMs-(performance.now()-workerStart);if(remaining>0){event.stopImmediatePropagation();setTimeout(()=>{const delayed=new MessageEvent('message',{data});Object.defineProperty(delayed,'floorDelivered',{value:true});this.dispatchEvent(delayed)},remaining);return;}}
if(data.type==='ready')proof.fps=data.fps;if(data.type==='state-history'&&data.requestId===900002)proof.localHistory=data.info;if(data.type==='state-exported'&&[900000,900001].includes(data.requestId))proof[data.requestId===900000?'controllerRam':'chatRam']=JSON.parse(new TextDecoder().decode(data.bytes.slice(72))).hardware.wram.slice(0,2);if(data.type==='state-hash'){const elapsed=performance.now()-hashAt;proof.admission.hashMs+=elapsed;proof.admission.hashMaxMs=Math.max(proof.admission.hashMaxMs,elapsed);proof.admission.hashCount++;proof.hashes.push(data.info);}if(data.type==='frame'&&data.epoch){workerPending=false;epochFrames++;if(window.scriptKey&&(data.frame+1)%60===0){window.dispatchEvent(new KeyboardEvent((data.frame+1)%120===0?'keyup':'keydown',{code:window.scriptKey}));proof.scriptedInputs=(proof.scriptedInputs||0)+1;}const now=performance.now(),elapsed=now-workerStart;proof.timing.workerMs+=elapsed;proof.timing.workerMax=Math.max(proof.timing.workerMax,elapsed);if(lastFrame){const bucket=Math.min(200,Math.round(now-lastFrame));proof.timing.frameGaps[bucket]=(proof.timing.frameGaps[bucket]||0)+1}lastFrame=now;proof.frameCount++;proof.frames.push({epoch:data.epoch,frame:data.frame});if(proof.frames.length>12)proof.frames.shift()}})}};
    const S=WebSocket;window.WebSocket=class extends S{send(data){const value=JSON.parse(data);if(['gameAbort','peerFailed'].includes(value.type))proof.workloadStopped=true;if(['join','joinCode','leave','gamePause','gameAbort','peerFailed','heartbeat'].includes(value.type))note('send',{type:value.type,reason:value.reason,frame:value.frame,sinceStart:epochAt?Math.round(performance.now()-epochAt):undefined,epochFrames});if(value.type==='gameReady')proof.gameReadies=(proof.gameReadies||0)+1;if(value.type==='gameAck'&&window.dropGameAck){proof.droppedAcks=(proof.droppedAcks||0)+1;return;}return super.send(data)}constructor(...a){super(...a);this.addEventListener('close',e=>{proof.workloadStopped=true;note('socket-close',{code:e.code})});this.addEventListener('message',event=>{const {data}=event,e=JSON.parse(data);if(['peerStop','gameStop'].includes(e.type))proof.workloadStopped=true;if(e.type==='gameStart')proof.workloadStopped=false;if(['peerStop','gameStop','gamePauseAt','gameStart'].includes(e.type))note('receive',{type:e.type,reason:e.reason});if(e.type==='gameStart'&&window.delayStart){window.delayStart=false;proof.delayedStarts=(proof.delayedStarts||0)+1;event.stopImmediatePropagation();setTimeout(()=>this.dispatchEvent(new MessageEvent('message',{data})),250);return;}if(e.type==='gameStart'){proof.activeEpoch=e.epoch;lastInputAt=0;proof.timing.delays.push(e.delay);lastFrame=0;epochAt=performance.now();epochFrames=0;}if(e.type==='room'){proof.room=e.room;proof.rooms.push({established:e.room.established,status:e.room.game?.status})}})}};
